version: '3'

services:
  web:
    build: .
    command: /bin/bash -c "source /pythonProject7/.venv/Scripts/activate && python /pythonProject7/jobsite/manage.py migrate && python /pythonProject7/jobsite/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/pythonProject7
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=jobsite.settings
